//go:build ignore

package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"io"
	"net/http"
	"os"
	"strings"
	"time"
)

// Data sources:
// - https://github.com/muan/unicode-emoji-json (name, slug, group, order)
// - https://github.com/muan/emojilib (keywords)

const (
	unicodeEmojiURL = "https://raw.githubusercontent.com/muan/unicode-emoji-json/main/data-by-emoji.json"
	orderedEmojiURL = "https://raw.githubusercontent.com/muan/unicode-emoji-json/main/data-ordered-emoji.json"
	keywordsURL     = "https://raw.githubusercontent.com/muan/emojilib/main/dist/emoji-en-US.json"
	outputPath      = "emojis.go"
)

type unicodeEmoji struct {
	Name  string `json:"name"`
	Slug  string `json:"slug"`
	Group string `json:"group"`
}

type emojiEntry struct {
	Name     string
	Slug     string
	Category string
	Char     string
	Keywords []string
}

func main() {
	entries, err := loadEmojis()
	if err != nil {
		fmt.Fprintf(os.Stderr, "error loading emoji data: %v\n", err)
		os.Exit(1)
	}

	content, err := render(entries)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error rendering %s: %v\n", outputPath, err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputPath, content, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing %s: %v\n", outputPath, err)
		os.Exit(1)
	}

	fmt.Printf("generated %s with %d emojis\n", outputPath, len(entries))
}

func loadEmojis() ([]emojiEntry, error) {
	var dataByEmoji map[string]unicodeEmoji
	if err := fetchJSON(unicodeEmojiURL, &dataByEmoji); err != nil {
		return nil, err
	}

	var orderedEmoji []string
	if err := fetchJSON(orderedEmojiURL, &orderedEmoji); err != nil {
		return nil, err
	}

	var keywordsByEmoji map[string][]string
	if err := fetchJSON(keywordsURL, &keywordsByEmoji); err != nil {
		return nil, err
	}

	entries := make([]emojiEntry, 0, len(orderedEmoji))
	for _, char := range orderedEmoji {
		meta, ok := dataByEmoji[char]
		if !ok {
			return nil, fmt.Errorf("missing unicode metadata for %q", char)
		}

		keywords, ok := keywordsByEmoji[char]
		if !ok {
			return nil, fmt.Errorf("missing keyword list for %q", char)
		}

		entries = append(entries, emojiEntry{
			Name:     meta.Name,
			Slug:     meta.Slug,
			Category: meta.Group,
			Char:     char,
			Keywords: keywords,
		})
	}

	return entries, nil
}

func fetchJSON(url string, v interface{}) error {
	client := &http.Client{Timeout: 30 * time.Second}

	resp, err := client.Get(url)
	if err != nil {
		return fmt.Errorf("GET %s: %w", url, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(io.LimitReader(resp.Body, 1024))
		return fmt.Errorf("GET %s: %s (%s)", url, resp.Status, strings.TrimSpace(string(body)))
	}

	if err := json.NewDecoder(resp.Body).Decode(v); err != nil {
		return fmt.Errorf("decode %s: %w", url, err)
	}

	return nil
}

func render(entries []emojiEntry) ([]byte, error) {
	var b bytes.Buffer

	b.WriteString("package turtle\n\n")
	b.WriteString("// Code generated by go run ./regenerate_emojis.go; DO NOT MANUALLY EDIT.\n")
	b.WriteString("\n")
	b.WriteString("// Emoji holds info about an emoji character\n")
	b.WriteString("type Emoji struct {\n")
	b.WriteString("\tName     string   `json:\"name\" toml:\"name\"`\n")
	b.WriteString("\tSlug     string   `json:\"slug\" toml:\"slug\"`\n")
	b.WriteString("\tCategory string   `json:\"category\" toml:\"category\"`\n")
	b.WriteString("\tChar     string   `json:\"char\" toml:\"char\"`\n")
	b.WriteString("\tKeywords []string `json:\"keywords\" toml:\"keywords\"`\n")
	b.WriteString("}\n\n")
	b.WriteString("// String implementation for Emoji\n")
	b.WriteString("func (e Emoji) String() string {\n")
	b.WriteString("\treturn e.Slug\n")
	b.WriteString("}\n\n")
	b.WriteString("// emojis holds all available Emoji\n")
	b.WriteString("var emojis = []*Emoji{\n")

	for _, emoji := range entries {
		fmt.Fprintf(&b, "\t{\n")
		fmt.Fprintf(&b, "\t\tName:     %s,\n", quoteLiteral(emoji.Name))
		fmt.Fprintf(&b, "\t\tSlug:     %s,\n", quoteLiteral(emoji.Slug))
		fmt.Fprintf(&b, "\t\tCategory: %s,\n", quoteLiteral(emoji.Category))
		fmt.Fprintf(&b, "\t\tChar:     %s,\n", quoteLiteral(emoji.Char))
		fmt.Fprintf(&b, "\t\tKeywords: []string{%s},\n", joinQuoted(emoji.Keywords))
		fmt.Fprintf(&b, "\t},\n")
	}

	b.WriteString("}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, err
	}

	return src, nil
}

func joinQuoted(values []string) string {
	var b strings.Builder

	for i, value := range values {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(quoteLiteral(value))
	}

	return b.String()
}

func quoteLiteral(value string) string {
	var b strings.Builder
	b.Grow(len(value) + 2)
	b.WriteByte('"')

	for _, r := range value {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			if r < 0x20 {
				fmt.Fprintf(&b, "\\u%04x", r)
				continue
			}
			b.WriteRune(r)
		}
	}

	b.WriteByte('"')
	return b.String()
}
